#!/usr/bin/python3.5

import sys


# Error handling

def help():
    print("\t-- Python project tester --\n")
    print("This script will help you to compare your project with another one.\n")
    print("USAGE:")
    print("\t./test_me [binary 1] [binary 2] [arguments ...]\n")
    print("Made by valentin.ichkour@epitech.eu")
    exit(84)


def check_open_file():
    try:
        open(sys.argv[1], 'r')
        open(sys.argv[2], 'r')
    except IOError:
        sys.stderr.write('Error: Could not found one of your binary\n')
        exit(84)


def start_script():
    print("Start!")


# Core


def core():
    try:
        check_open_file()
        start_script()
    except IndexError:
        print("Error: List index out of range.")
        exit(84)
    except IOError as e:
        print ("I/O error({}): {}".format(e.errno, e.strerror))
        exit(84)
    except ValueError:
        print ("Could not convert data to an integer.")
        exit(84)
    except OverflowError:
        print("Math range error.")
        exit(84)


# Main


if __name__ == '__main__':
    if len(sys.argv) < 3 or sys.argv[1] == "-h":
        help()
    else:
        core()